version: "3.9"
services:
  db:
    image: "postgres:alpine"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "jurassic"
      POSTGRES_USER: "jurassicdbuser"
      POSTGRES_PASSWORD: "jurassicdbpassword"
